version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  backend:
    image: mayank7833/backend-image:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=${{ MONGODB_URL }}

  frontend:
    image: mayank7833/frontend-image:latest
    ports:
      - "3000:3000"
 



volumes:
  mongodb-data: