name: 3-tier-app-CI/CD

on:
  push:
    branches:
      - testing 
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Install frontend Dependencies
        run: |
          cd task-manager-frontend  
          ls | cat simplefile.txt
          npm install

      - name: Install backend Dependencies 
        run: |
          cd task-manager-backend 
          ls | cat simplefile.txt
          npm install          

      - name: Run backend unit Tests
        run: |
            cd task-manager-backend  
            echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" > .env 
            npm test
  
  
      
      - name: Create SonarCloud configuration file
        run: |
          echo "sonar.projectKey=${{ secrets.SONARPROJECT}}" > sonar-project.properties
          echo "sonar.organization=${{ secrets.SONARORGANIZATION}} >> sonar-project.properties
          echo "sonar.sources=task-manager-backend,task-manager-frontend" >> sonar-project.properties
            
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUBTOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

