name: 3-tier-app-CI/CD

on:
  push:
    branches:
      - testing 
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Install frontend Dependencies
        run: |
          cd task-manager-frontend  
          ls | cat simplefile.txt
          npm install

      - name: Install backend Dependencies 
        run: |
          cd task-manager-backend 
          ls | cat simplefile.txt
          npm install          

      - name: Run backend unit Tests
        run: |
          cd task-manager-backend  
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" > .env 
          npm test

      - name: Analyze code with SonarCloud (Backend)
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          organization: "${{ secrets.SONARORGANIZATION }}" 
          projectKey: "${{ secrets.SONARPROJECT }}"     
          projectBaseDir: "task-manager-backend"  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
      - name: Analyze code with SonarCloud (Frontend)
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          organization: "${{ secrets.SONARORGANIZATION }}" 
          projectKey: "${{ secrets.SONARPROJECT }}"      
          projectBaseDir: "task-manager-frontend"  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Setup Maven
        uses: actions/setup-java@v2
        with:
            distribution: 'adopt'
            java-version: '11'
