name: 3-tier-app-CI/CD

on:
  push:
    branches:
      - testing 
    
  
jobs:
  build:
    runs-on: ubuntu-latest
   

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2

      with:
        node-version: '20'

    - name: Install frontend Dependencies
      run: |
        cd To_do-list/task-manager-frontend  # Change this to the path of your frontend
        ls | cat simplefile.txt
        npm install

    - name: Install backend Dependencies 
      run: |
        cd To_do-list/task-manager-backend # Change this to the path of your frontend
        ls | cat simplefile.txt
        npm install          
             
    - name: Run backend unit  Tests
      run: |
          
          cd task-manager-backend  # Change this to the path of your frontend
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" > .env 
          npm test
