name: 3-tier-app-CI/CD

on:
  push:
    branches:
      - testing 
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Install frontend Dependencies
        run: |
          cd task-manager-frontend  
          ls | cat simplefile.txt
          npm install

      - name: Install backend Dependencies 
        run: |
          cd task-manager-backend 
          ls | cat simplefile.txt
          npm install          

      - name: Run backend unit Tests
        run: |
            cd task-manager-backend  
            echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" > .env 
            npm test
            
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUBTOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: 
            -Dsonar.organization=${{ secrets.SONARORGANIZATION}}
            -Dsonar.projectKey=${{ secrets.SONARPROJECT}}
            -Dsonar.sources=task-manager-backend,task-manager-frontend 

